name: android

on:
  workflow_dispatch:
  push:
    paths: 
      - build/**
      - .github/workflows/android.yml

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build
        run: |
          cd build
          ./make_android_lua53.sh
      - name: Upload53
        uses: actions/upload-artifact@v4
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53   
