name: osxbuild

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/osx.yml

jobs:
  osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build
          ./make_osx_lua54.sh
          ./make_osx_lua53.sh
          ./make_osx_luajit.sh
          ./make_osx_silicon_lua53.sh
          ./make_osx_silicon_lua54.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./build/plugin_lua54/**/*
          name: plugin_lua54
      - name: Upload53
        uses: actions/upload-artifact@v4
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53   
      - name: UploadJit
        uses: actions/upload-artifact@v4
        with:
          path: ./build/plugin_luajit/**/*
          name: plugin_luajit
