name: test

on: 
  push:
    paths: 
      - test/**
      - .github/workflows/test.yml

jobs:
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd build/luac
          ./make_unix.sh
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./build/luac/build_unix/**/*
          name: plugin_luac
    

   
